export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum UserRole {
  EMPLOYEE = 'EMPLOYEE',
  PAYROLL_SPECIALIST = 'PAYROLL_SPECIALIST',
  PAYROLL_MANAGER = 'PAYROLL_MANAGER',
  HR_MANAGER = 'HR_MANAGER',
  LEGAL_ADMIN = 'LEGAL_ADMIN',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  FINANCE_STAFF = 'FINANCE_STAFF',
}

export enum AllowanceType {
  TRANSPORTATION = 'TRANSPORTATION',
  HOUSING = 'HOUSING',
  FOOD = 'FOOD',
  COMMUNICATION = 'COMMUNICATION',
  EDUCATION = 'EDUCATION',
  SPECIAL_ASSIGNMENT = 'SPECIAL_ASSIGNMENT',
  OTHER = 'OTHER',
}

export enum CalculationMethod {
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE',
  HOURLY = 'HOURLY',
}

export enum PaymentFrequency {
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  ANNUAL = 'ANNUAL',
  ONE_TIME = 'ONE_TIME',
}